name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t docker-image .

      - name: Create .tar.gz archive
        run: |
          docker save docker-image | gzip > docker-image.tar.gz
      - name: Upload docker archive to Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: docker-image
          path: docker-image.tar.gz

  # If you wish to deploy the .tar.gz archive elsewhere, or only wish to have it in artifacts, change or remove the below
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: docker-image
          path: docker-image.tar.gz

      # You may want to look into hosting your own Docker registry, or using a completely free one like https://treescale.com/ for private packages - for this, you'll need to modify or replace the below step.
      # If you wish to use Docker Hub, you'll also need to change the below.
      - name: Push Docker image to GitHub Packages
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag docker-image ghcr.io/${REPO_LOWER}/docker-image:latest
          docker push docker.pkg.github.com/${REPO_LOWER}/docker-image:latest
